### ISSUE TITLE
关于滑动不加载

### ISSUE THREAD

**Issue by gpfduoduo** [kymjs/CodeCafe#2]
你好，看过了你的代码关于滑动不加载的部分，这样好像有问题，每次停下来都调用adapter的notifyDataSetChanged()函数，这样效果很不好 ，一般的图片加载都会闪动

**Comment by autoool** [comment]
我把BaseAdapter的这段代码删掉了。recyclerview 每行同一位置图片是有的有，有的没有。发现recyclerview 原来没有图片的地方，滑动一下，也会把图片加载出来。把这段代码删掉就没问题了。
  v.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
                isScrolling = !(newState == RecyclerView.SCROLL_STATE_IDLE);
                if (!isScrolling) {
                    notifyDataSetChanged();
                }
            }
        });

@kymjs 是的，我大意了。

**Comment by kymjs** [comment]
@gpfduoduo 图片加载回调里面判断，如果内存缓存有就不加载。见demo里的写法。

@chaozaiai 你代码的问题，滑动一会有一会没有那是item复用的问题。
